### ISSUE TITLE
support python3

### ISSUE THREAD

**Issue by ikamensh** [taichino/jcconv#12]
Hello, I got following error during installation:

Collecting jcconv (from -r requirements.txt (line 21))
  Downloading https://files.pythonhosted.org/packages/dd/5b/55d6dd385e8584c6750864ddec8d5ff82a295b37ac68344febc9e923bf99/jcconv-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0m/kzql0npd4bqgnc24_2slnpz02kbyyc/T/pip-install-pdidqiqm/jcconv/setup.py", line 17
        print "unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0m/kzql0npd4bqgnc24_2slnpz02kbyyc/T/pip-install-pdidqiqm/jcconv/
You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by LIQRGV** [comment]
Hi @ikamensh, 
you can use https://pypi.org/project/jcconv3/ instead.
